### ISSUE TITLE
Support discovering network policy according to the drop reason

### ISSUE THREAD

**Issue by seungsoo-lee** [accuknox/auto-policy-discovery#238]
Basically, knoxAutoPolicy discovers the network policy based on the network log that is the result PASS.

But, we need to support the functionality that can discover the network policy from the dropped network log as well.

There can be some types of drop reasons.

- there is no matched policy.
- there is a deny policy.

 - [ ] We should provide a configuration that how much cover the dropped network log: no matched only / all dropped logs

**Comment by nyrahul** [comment]
This is handled in the code. Tested and verified.
