### ISSUE TITLE
maybe exclude rule G402 from gosec in CI?

### ISSUE THREAD

**Issue by humancalico** [accuknox/auto-policy-discovery#345]

**Comment by nyrahul** [comment]
We now have applied a `// #nosec G402` exception to [the specific line](https://github.com/accuknox/auto-policy-discovery/blob/0ae0ac5f36dbb23703e9b5245b96dc76674c8e2d/src/cluster/clusterMgmtHandler.go#L79) generating that error. We do not anymore get the gosec error in CI.
