### ISSUE TITLE
storage of logs

### ISSUE THREAD

**Issue by humancalico** [accuknox/auto-policy-discovery#348]
Currently the logs retrieved from the feeder service (or hubble or kubearmor-relay) are stored in a global variable which is emptied once the operation trigger is hit. This would work fine if the operation trigger is low but might cause issues when the operation trigger is high.
https://github.com/accuknox/knoxAutoPolicy/blob/9758ef048e5eb14fe0244a30ac96753a01aad294/src/plugin/kubearmor.go#L18-L22
https://github.com/accuknox/knoxAutoPolicy/blob/9758ef048e5eb14fe0244a30ac96753a01aad294/src/plugin/cilium.go#L60-L63
cc @daemon1024

**Comment by nyrahul** [comment]
Setting a too large operation-trigger is a configuration mistake. If someone sets too large operation-trigger then one has to accordingly provision large memory resources for policy-discovery.
